### ISSUE TITLE
Metadata rendered and copied is executed if it is code

### ISSUE THREAD

**Issue by brucejh99** [brucejh99/inCite#16]
![image](https://user-images.githubusercontent.com/32785837/53314778-204dec80-388e-11e9-8404-6837963a3f21.png)
The title above is from the link https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date. It renders an input box and copies nothing in that area. Let's parse it and clean it up for copy + render and apply it to every piece of metadata (without getting rid of our own styling).

**Comment by ddlan** [comment]
Fixed by commit e0c29490f7fbd2b5f780dd76b2c8fa4af12671bc
