### ISSUE TITLE
Bug with getting the date

### ISSUE THREAD

**Issue by brucejh99** [brucejh99/inCite#2]
![image](https://user-images.githubusercontent.com/32785837/50368220-42588500-0554-11e9-9d10-666e5a5164c2.png)

**Comment by brucejh99** [comment]
Fixed with a try-catch returning an empty string instead of trying to convert null to an HTML date

**Comment by ddlan** [comment]
Added a timezone conversion the first time you load the citation page so the correct date is applied.

**Comment by ddlan** [comment]
Added a timezone conversion when you first open the citation page so the correct date is displayed.
