### ISSUE TITLE
Bibliography name validation

### ISSUE THREAD

**Issue by ddlan** [brucejh99/inCite#28]
Right now users can type in no bibliography name (maybe this is acceptable behavior).

Also, if they put a name that is too long, the name takes up multiple lines on the bibliography page.
<img width="358" alt="bug" src="https://user-images.githubusercontent.com/25760929/56184875-93432c00-5fd0-11e9-9622-d04de1584955.png">

**Comment by brucejh99** [comment]
Resolved by ending bibliography names with long names with ellipses
