### ISSUE TITLE
Sorting functions are wrong

### ISSUE THREAD

**Issue by brucejh99** [brucejh99/inCite#7]
Sorts MLA and APA in the wrong order.
![image](https://user-images.githubusercontent.com/32785837/51794627-9df5de00-21a4-11e9-9bbf-aa35d58f97c4.png)
We should probably refactor this anyway.

**Comment by ddlan** [comment]
Changed the converting and sorting algorithm so converter is called when adding the citation for the first time and generates the formatted strings to use for the sorter. Then, only the sorter is called when switching citation styles.

**Comment by brucejh99** [comment]
Shouldn't generator also be called when switching styles to update the format to the new style?
